services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile-api
    container_name: fastapi_service
    ports:
      - "8000:8000"
    networks:
      - app-network
    restart: always
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db/${MYSQL_DATABASE}
    volumes:
      - ./api:/app
      - ./db:/app/db
    depends_on:
      - db

  streamlit:
    build:
      context: ./ui
      dockerfile: Dockerfile
    container_name: streamlit_service
    ports:
      - "8501:8501"
    volumes:
      - ./ui:/app
    depends_on:
      - fastapi
    networks:
      - app-network
    restart: always

  db:
    image: mariadb:latest
    container_name: db_service
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db_data:/var/lib/mysql
    ports:
      - "5432:5432"

networks:
  app-network:
    driver: bridge
